//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputSystem_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystem_Actions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystem_Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem_Actions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""df70fa95-8a34-4494-b137-73ab6b9c7d37"",
            ""actions"": [
                {
                    ""name"": ""Move_Left"",
                    ""type"": ""Value"",
                    ""id"": ""1569956c-ea9d-4242-bbbf-d942934740f9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move_Right"",
                    ""type"": ""Value"",
                    ""id"": ""39d188cc-d563-48a9-b317-186b016e1ead"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""776f8994-5b63-4056-9fff-ecebc4057b6f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Unplug_Slot_1"",
                    ""type"": ""Button"",
                    ""id"": ""68682353-5a15-4d16-9b0f-1e4a980dd884"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Unplug_Slot_2"",
                    ""type"": ""Button"",
                    ""id"": ""7ece79d6-fcf1-48a2-ac85-302346f6ee3b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Unplug_Slot_3"",
                    ""type"": ""Button"",
                    ""id"": ""ffa600db-3a02-4a12-85b8-40ad85a3cefd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Plug_Red"",
                    ""type"": ""Button"",
                    ""id"": ""171f0acb-02fd-4cce-bc2e-cde3d84eac2d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Plug_Green"",
                    ""type"": ""Button"",
                    ""id"": ""f2c8b344-990e-431f-bb56-ee6811d25ca8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Plug_Blue"",
                    ""type"": ""Button"",
                    ""id"": ""4f1030b4-f7c3-4715-8ef1-52fc14a0b1f5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""351e1e04-ff82-4db9-a1c5-64fab5eff0d4"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3623ab17-2657-40c3-85aa-3cda4771c9cf"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34d17e2f-45ca-4b0f-a81a-bac70b09fcf5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b694a4e-fdb3-475c-9750-e0b74161d436"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unplug_Slot_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2d15f33-b684-4b5a-9ff5-ba89689cb42c"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unplug_Slot_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caace9bc-7dfe-4350-98ff-593b5e195cfb"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unplug_Slot_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2ce27c0-bb3a-40b2-a131-764018f4a7ef"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Plug_Red"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef03d191-5a30-4b83-8f80-7ad07f52a14f"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Plug_Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b363c944-276b-49ca-91ad-c983967632ce"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Plug_Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move_Left = m_Player.FindAction("Move_Left", throwIfNotFound: true);
        m_Player_Move_Right = m_Player.FindAction("Move_Right", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Unplug_Slot_1 = m_Player.FindAction("Unplug_Slot_1", throwIfNotFound: true);
        m_Player_Unplug_Slot_2 = m_Player.FindAction("Unplug_Slot_2", throwIfNotFound: true);
        m_Player_Unplug_Slot_3 = m_Player.FindAction("Unplug_Slot_3", throwIfNotFound: true);
        m_Player_Plug_Red = m_Player.FindAction("Plug_Red", throwIfNotFound: true);
        m_Player_Plug_Green = m_Player.FindAction("Plug_Green", throwIfNotFound: true);
        m_Player_Plug_Blue = m_Player.FindAction("Plug_Blue", throwIfNotFound: true);
    }

    ~@InputSystem_Actions()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, InputSystem_Actions.Player.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move_Left;
    private readonly InputAction m_Player_Move_Right;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Unplug_Slot_1;
    private readonly InputAction m_Player_Unplug_Slot_2;
    private readonly InputAction m_Player_Unplug_Slot_3;
    private readonly InputAction m_Player_Plug_Red;
    private readonly InputAction m_Player_Plug_Green;
    private readonly InputAction m_Player_Plug_Blue;
    public struct PlayerActions
    {
        private @InputSystem_Actions m_Wrapper;
        public PlayerActions(@InputSystem_Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move_Left => m_Wrapper.m_Player_Move_Left;
        public InputAction @Move_Right => m_Wrapper.m_Player_Move_Right;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Unplug_Slot_1 => m_Wrapper.m_Player_Unplug_Slot_1;
        public InputAction @Unplug_Slot_2 => m_Wrapper.m_Player_Unplug_Slot_2;
        public InputAction @Unplug_Slot_3 => m_Wrapper.m_Player_Unplug_Slot_3;
        public InputAction @Plug_Red => m_Wrapper.m_Player_Plug_Red;
        public InputAction @Plug_Green => m_Wrapper.m_Player_Plug_Green;
        public InputAction @Plug_Blue => m_Wrapper.m_Player_Plug_Blue;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move_Left.started += instance.OnMove_Left;
            @Move_Left.performed += instance.OnMove_Left;
            @Move_Left.canceled += instance.OnMove_Left;
            @Move_Right.started += instance.OnMove_Right;
            @Move_Right.performed += instance.OnMove_Right;
            @Move_Right.canceled += instance.OnMove_Right;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Unplug_Slot_1.started += instance.OnUnplug_Slot_1;
            @Unplug_Slot_1.performed += instance.OnUnplug_Slot_1;
            @Unplug_Slot_1.canceled += instance.OnUnplug_Slot_1;
            @Unplug_Slot_2.started += instance.OnUnplug_Slot_2;
            @Unplug_Slot_2.performed += instance.OnUnplug_Slot_2;
            @Unplug_Slot_2.canceled += instance.OnUnplug_Slot_2;
            @Unplug_Slot_3.started += instance.OnUnplug_Slot_3;
            @Unplug_Slot_3.performed += instance.OnUnplug_Slot_3;
            @Unplug_Slot_3.canceled += instance.OnUnplug_Slot_3;
            @Plug_Red.started += instance.OnPlug_Red;
            @Plug_Red.performed += instance.OnPlug_Red;
            @Plug_Red.canceled += instance.OnPlug_Red;
            @Plug_Green.started += instance.OnPlug_Green;
            @Plug_Green.performed += instance.OnPlug_Green;
            @Plug_Green.canceled += instance.OnPlug_Green;
            @Plug_Blue.started += instance.OnPlug_Blue;
            @Plug_Blue.performed += instance.OnPlug_Blue;
            @Plug_Blue.canceled += instance.OnPlug_Blue;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move_Left.started -= instance.OnMove_Left;
            @Move_Left.performed -= instance.OnMove_Left;
            @Move_Left.canceled -= instance.OnMove_Left;
            @Move_Right.started -= instance.OnMove_Right;
            @Move_Right.performed -= instance.OnMove_Right;
            @Move_Right.canceled -= instance.OnMove_Right;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Unplug_Slot_1.started -= instance.OnUnplug_Slot_1;
            @Unplug_Slot_1.performed -= instance.OnUnplug_Slot_1;
            @Unplug_Slot_1.canceled -= instance.OnUnplug_Slot_1;
            @Unplug_Slot_2.started -= instance.OnUnplug_Slot_2;
            @Unplug_Slot_2.performed -= instance.OnUnplug_Slot_2;
            @Unplug_Slot_2.canceled -= instance.OnUnplug_Slot_2;
            @Unplug_Slot_3.started -= instance.OnUnplug_Slot_3;
            @Unplug_Slot_3.performed -= instance.OnUnplug_Slot_3;
            @Unplug_Slot_3.canceled -= instance.OnUnplug_Slot_3;
            @Plug_Red.started -= instance.OnPlug_Red;
            @Plug_Red.performed -= instance.OnPlug_Red;
            @Plug_Red.canceled -= instance.OnPlug_Red;
            @Plug_Green.started -= instance.OnPlug_Green;
            @Plug_Green.performed -= instance.OnPlug_Green;
            @Plug_Green.canceled -= instance.OnPlug_Green;
            @Plug_Blue.started -= instance.OnPlug_Blue;
            @Plug_Blue.performed -= instance.OnPlug_Blue;
            @Plug_Blue.canceled -= instance.OnPlug_Blue;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove_Left(InputAction.CallbackContext context);
        void OnMove_Right(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnUnplug_Slot_1(InputAction.CallbackContext context);
        void OnUnplug_Slot_2(InputAction.CallbackContext context);
        void OnUnplug_Slot_3(InputAction.CallbackContext context);
        void OnPlug_Red(InputAction.CallbackContext context);
        void OnPlug_Green(InputAction.CallbackContext context);
        void OnPlug_Blue(InputAction.CallbackContext context);
    }
}
